In [5]:
import numpy as np
import pandas as pd
import matplotlib as plt
import EigenPro2.mnist as mnist
from sklearn import metrics
import math
import time

In [6]:
(train_x, train_y), (test_x, test_y) = mnist.load()



Load MNIST dataset.
60000 train samples
10000 test samples


In [7]:
X_temp=[]
X=[]
Y=[]
Y_temp=[]
for i in range(60000):
    if train_y[i] ==2:
        
        temp=train_x[i].flatten()
        temp2=-1
        X_temp.append(temp)
        Y_temp.append(temp2)
    elif train_y[i]==5:
        temp=train_x[i].flatten()
        temp2=1
        X_temp.append(temp)
        Y_temp.append(temp2)


for i in range(5000):
    Y.append(Y_temp[i])
    X.append(X_temp[i])

In [8]:
X_test=[]
Y_test=[]
for i in range(10000):
    if test_y[i] ==2:
        
        temp=train_x[i].flatten()
        temp2=-1
        X_test.append(temp)
        Y_test.append(temp2)
    elif test_y[i]==5:
        temp=train_x[i].flatten()
        temp2=1
        X_test.append(temp)
        Y_test.append(temp2)
y_bar=np.average(Y_test)
print(len(Y_test))

1924


In [9]:
print(X[0])
print(X_test[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [10]:
def K(x,y):
    return math.exp(-(np.linalg.norm(x-y))**2/(784))

In [11]:
np.linalg.norm(X[0]-X[1])**2/784

0.13080199860582886

In [12]:
math.exp(-0.10930)

0.8964614387218198

In [13]:
b=[]
for x in X_test:
    row=[]
    for y in X:
        row.append(K(x,y))
    b.append(row)
b=np.matrix(b)
print(b) 

[[0.89424443 0.86877089 0.85742606 ... 0.85753907 0.87116216 0.86020274]
 [0.895243   0.88630037 0.92108927 ... 0.88002821 0.87375413 0.90711363]
 [0.87331027 0.89888311 0.88429786 ... 0.83765678 0.83240107 0.85992864]
 ...
 [0.88939254 0.87726911 0.86893513 ... 0.85240437 0.83350277 0.87242403]
 [0.90043922 0.86793937 0.86857843 ... 0.87168982 0.8506915  0.85603505]
 [0.88707152 0.90493872 0.89522779 ... 0.88620007 0.85979927 0.90823083]]


In [14]:

k=[]
for i in range(5000):
    row=[]
    for j in range(5000):
        row.append(K(X[i],X[j]))
    #Row=np.array(row)
    k.append(row)
    
k=np.matrix(k)
print(k)
k_inv=np.linalg.inv(k)
print(k_inv)


[[1.         0.87739148 0.85104817 ... 0.88084355 0.86142919 0.88322513]
 [0.87739148 1.         0.8883275  ... 0.864557   0.85205539 0.88526047]
 [0.85104817 0.8883275  1.         ... 0.87609548 0.88406696 0.88037279]
 ...
 [0.88084355 0.864557   0.87609548 ... 1.         0.84560682 0.89386549]
 [0.86142919 0.85205539 0.88406696 ... 0.84560682 1.         0.87842255]
 [0.88322513 0.88526047 0.88037279 ... 0.89386549 0.87842255 1.        ]]
[[ 4.10023265e+02 -1.32543160e+00  4.29498098e+00 ... -2.14696366e+00
  -1.24853890e+00  7.25272811e-02]
 [-1.32543160e+00  6.60209254e+02 -7.46923205e+00 ...  8.37425029e+00
  -3.85162740e+00 -3.20462691e-01]
 [ 4.29498098e+00 -7.46923205e+00  1.28757842e+03 ...  3.61486548e+00
   1.70939764e+00 -7.54627265e+00]
 ...
 [-2.14696366e+00  8.37425029e+00  3.61486548e+00 ...  8.85254378e+02
   2.21947445e+00  2.69775289e+00]
 [-1.24853890e+00 -3.85162740e+00  1.70939764e+00 ...  2.21947445e+00
   1.82562193e+02  2.70370217e+00]
 [ 7.25272810e-02 -3.20462

In [15]:
y=np.array(Y)



In [16]:
temp1=np.matmul(b,k_inv)

In [17]:
temp2=np.matmul(temp1,y)
print(temp2)
temp2=np.ravel(temp2)
print(temp2)

[[-0.2126493   0.54439598 -0.65275565 ... -0.63513158  1.
   0.03308726]]
[-0.2126493   0.54439598 -0.65275565 ... -0.63513158  1.
  0.03308726]


In [18]:
mis=[]
for i in range(1924):
    if np.sign(temp2[i])==np.sign(Y_test[i]):
        mis.append(i)
print(len(mis))

973


-1
