In [39]:
import numpy as np
import pandas as pd
import matplotlib as plt
import EigenPro2.mnist as mnist
from sklearn import metrics
import math
import time

In [40]:
(x_train, y_train), (x_test, y_test) = mnist.load()

Load MNIST dataset.
60000 train samples
10000 test samples


In [41]:
Xtemp=[]
Ytemp=[]
X=[]
Y=[]
for i in range(60000):
    if y_train[i]==2:
        temp=x_train[i].flatten()
        temp2=-1
        Xtemp.append(temp)
        Ytemp.append(temp2)
    if y_train[i]==5:
        temp=x_train[i].flatten()
        temp2=1
        Xtemp.append(temp)
        Ytemp.append(temp2)
for i in range(5):
    X.append(Xtemp[i])
    Y.append(Ytemp[i])
        

In [42]:
Xtest=[]
Ytest=[]
for i in range(10000):
    if y_test[i]==2:
        temp=x_test[i].flatten()
        temp2=-1
        Xtest.append(temp)
        Ytest.append(temp2)
    if y_test[i]==5:
        temp=x_test[i].flatten()
        temp2=1
        Xtest.append(temp)
        Ytest.append(temp2)
        

In [43]:
def K(x,y):
    return math.exp(-(np.linalg.norm(x-y))**2/(784))

In [61]:
a=[]
for i in range(5):
    a.append(K(Xtest[0],X[i]))
print(a)

[0.852215023405123, 0.8428625983347651, 0.8744416990767535, 0.8533174639203265, 0.8864215430826421]


In [69]:
b=[]
for i in range(5):
    row=[]
    for j in range(5):
        row.append(K(X[i],X[j]))
    b.append(row)
    print(row)
m=np.matrix(b)
print(m)
m_inv=np.linalg.inv(m)
print(m_inv)


[1.0, 0.8773914819299646, 0.8510481742278658, 0.8887318426644698, 0.8638775176787447]
[0.8773914819299646, 1.0, 0.8883275027502059, 0.8998138131180171, 0.8713126968252196]
[0.8510481742278658, 0.8883275027502059, 1.0, 0.8838052771320531, 0.8544648413403485]
[0.8887318426644698, 0.8998138131180171, 0.8838052771320531, 1.0, 0.8706971815088328]
[0.8638775176787447, 0.8713126968252196, 0.8544648413403485, 0.8706971815088328, 1.0]
[[1.         0.87739148 0.85104817 0.88873184 0.86387752]
 [0.87739148 1.         0.8883275  0.89981381 0.8713127 ]
 [0.85104817 0.8883275  1.         0.88380528 0.85446484]
 [0.88873184 0.89981381 0.88380528 1.         0.87069718]
 [0.86387752 0.8713127  0.85446484 0.87069718 1.        ]]
[[ 6.16387197 -1.5108654  -0.60986953 -2.24551301 -1.53212029]
 [-1.5108654   7.61909414 -2.23605439 -2.30095417 -1.41934664]
 [-0.60986953 -2.23605439  6.13467756 -1.89696355 -1.11503031]
 [-2.24551301 -2.30095417 -1.89696355  7.84126024 -1.26177574]
 [-1.53212029 -1.41934664 -

In [46]:
y=np.array(Y)
print(y)

[ 1 -1  1 -1 -1]


In [63]:
temp=a@m_inv
print(temp)

[[ 0.17195711 -0.04261573  0.35289226  0.06078694  0.42054224]]


In [64]:
temp2=np.matmul(temp,y)
print(temp2)

[[0.08613592]]


In [65]:
print(Ytest[0])

-1
